# postgresql configurations
spring.datasource.url=jdbc:postgresql://dpg-dac04q2jnfac73egtqq0-a.frankfurt-postgres.render.com/moneymap_3ruz
spring.datasource.username=moneymap_3ruz_user
spring.datasource.password=${RENDER_DB_PASSWORD}